### ISSUE TITLE
Weird crashes when using with applied energistics 2

### ISSUE THREAD

**Issue by shinjitumala** [branchpanic/stockpile#111]
I connected export buses and storage buses on stockpiles and now I cannot run my world without crashing in 2 seconds.

Looks like something to do with the export buses.

<details>
<summary>Logs including all details</summary>
--- Minecraft Crash Report ----
// You're mean.

Time: 11/21/21, 7:25 PM
Description: Ticking GridNode

java.lang.RuntimeException: Encountered an exception while invoking a transaction close callback.
	at net.fabricmc.fabric.impl.transfer.transaction.TransactionManagerImpl$TransactionImpl.close(TransactionManagerImpl.java:135)
	at net.fabricmc.fabric.impl.transfer.transaction.TransactionManagerImpl$TransactionImpl.abort(TransactionManagerImpl.java:172)
	at net.fabricmc.fabric.impl.transfer.transaction.TransactionManagerImpl$TransactionImpl.close(TransactionManagerImpl.java:183)
	at appeng.api.inventories.PlatformInventoryWrapper.addItems(PlatformInventoryWrapper.java:201)
	at appeng.api.inventories.ItemTransfer.simulateAdd(ItemTransfer.java:63)
	at appeng.parts.automation.ExportBusPart.pushItemIntoTarget(ExportBusPart.java:265)
	at appeng.parts.automation.ExportBusPart.doBusWork(ExportBusPart.java:163)
	at appeng.parts.automation.SharedItemBusPart.tickingRequest(SharedItemBusPart.java:113)
	at appeng.me.service.TickManagerService.unsafeTickingRequest(TickManagerService.java:325)
	at appeng.me.service.TickManagerService.tickQueue(TickManagerService.java:116)
	at appeng.me.service.TickManagerService.tickLevelQueue(TickManagerService.java:93)
	at appeng.me.service.TickManagerService.onLevelEndTick(TickManagerService.java:78)
	at appeng.me.Grid.onLevelEndTick(Grid.java:252)
	at appeng.hooks.ticking.TickHandler.onServerLevelTickEnd(TickHandler.java:240)
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerTickEvents.lambda$static$6(ServerTickEvents.java:108)
	at net.minecraft.class_1937.handler$cak000$tickWorldAfterBlockEntities(class_1937.java:4094)
	at net.minecraft.class_1937.method_18471(class_1937.java:479)
	at net.minecraft.class_3218.method_18765(class_3218.java:422)
	at net.minecraft.server.MinecraftServer.redirect$coj000$fixUpdateSuppressionCrashTick(MinecraftServer.java:9284)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:891)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:831)
	at net.minecraft.class_1132.method_3748(class_1132.java:96)
	at net.minecraft.server.MinecraftServer.handler$chl000$modifiedRunLoop(MinecraftServer.java:8390)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:676)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: java.lang.IllegalStateException: The FixedItemInv class me.branchpanic.mods.stockpile.impl.attribute.FixedMassItemInv didn't accept the stack 1 air in slot 0! The inventory may be in a duped (invalid) state!
	at alexiil.mc.lib.attributes.item.compat.InventoryFixedWrapper.setInvStackInternal(InventoryFixedWrapper.java:116)
	at alexiil.mc.lib.attributes.item.compat.InventoryFixedWrapper.method_5447(InventoryFixedWrapper.java:97)
	at me.branchpanic.mods.stockpile.content.blockentity.ItemBarrelBlockEntity.method_5447(ItemBarrelBlockEntity.kt:196)
	at net.fabricmc.fabric.impl.transfer.item.InventorySlotWrapper.setStack(InventorySlotWrapper.java:51)
	at net.fabricmc.fabric.api.transfer.v1.item.base.SingleStackStorage.readSnapshot(SingleStackStorage.java:166)
	at net.fabricmc.fabric.api.transfer.v1.item.base.SingleStackStorage.readSnapshot(SingleStackStorage.java:42)
	at net.fabricmc.fabric.api.transfer.v1.transaction.base.SnapshotParticipant.onClose(SnapshotParticipant.java:105)
	at net.fabricmc.fabric.impl.transfer.transaction.TransactionManagerImpl$TransactionImpl.close(TransactionManagerImpl.java:132)
	... 25 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.fabricmc.fabric.impl.transfer.transaction.TransactionManagerImpl$TransactionImpl.close(TransactionManagerImpl.java:135)
	at net.fabricmc.fabric.impl.transfer.transaction.TransactionManagerImpl$TransactionImpl.abort(TransactionManagerImpl.java:172)
	at net.fabricmc.fabric.impl.transfer.transaction.TransactionManagerImpl$TransactionImpl.close(TransactionManagerImpl.java:183)
	at appeng.api.inventories.PlatformInventoryWrapper.addItems(PlatformInventoryWrapper.java:201)
	at appeng.api.inventories.ItemTransfer.simulateAdd(ItemTransfer.java:63)
	at appeng.parts.automation.ExportBusPart.pushItemIntoTarget(ExportBusPart.java:265)
	at appeng.parts.automation.ExportBusPart.doBusWork(ExportBusPart.java:163)
	at appeng.parts.automation.SharedItemBusPart.tickingRequest(SharedItemBusPart.java:113)

-- ExportBusPart being ticked. --
Details:
	Part Side: north
	CurrentTickRate: 60
	MinTickRate: 5
	MaxTickRate: 60
	Node: node hosted by appeng.parts.automation.ExportBusPart
	ConnectedSides: []
Stacktrace:
	at appeng.me.service.TickManagerService.unsafeTickingRequest(TickManagerService.java:325)
	at appeng.me.service.TickManagerService.tickQueue(TickManagerService.java:116)
	at appeng.me.service.TickManagerService.tickLevelQueue(TickManagerService.java:93)
	at appeng.me.service.TickManagerService.onLevelEndTick(TickManagerService.java:78)
	at appeng.me.Grid.onLevelEndTick(Grid.java:252)
	at appeng.hooks.ticking.TickHandler.onServerLevelTickEnd(TickHandler.java:240)
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerTickEvents.lambda$static$6(ServerTickEvents.java:108)
	at net.minecraft.class_1937.handler$cak000$tickWorldAfterBlockEntities(class_1937.java:4094)
	at net.minecraft.class_1937.method_18471(class_1937.java:479)
	at net.minecraft.class_3218.method_18765(class_3218.java:422)
	at net.minecraft.server.MinecraftServer.redirect$coj000$fixUpdateSuppressionCrashTick(MinecraftServer.java:9284)

-- Affected level --
Details:
	All players: 1 total; [class_3222['FunnyPigRun'/153, l='ServerWorld minecraft:overworld FPR3', x=-8211.94, y=-63.00, z=-37900.96]]
	Chunk stats: 3631
	Level dimension: minecraft:overworld
	Level spawn location: World: (-8216,63,-37681), Section: (at 8,15,15 in -514,3,-2356; chunk contains blocks -8224,-64,-37696 to -8209,319,-37681), Region: (-17,-74; contains chunks -544,-2368 to -513,-2337, blocks -8704,-64,-37888 to -8193,319,-37377)
	Level time: 4343497 game time, 4618168 day time
	Level name: FPR3
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 14208 (now: true), thunder time: 121839 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:891)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:831)
	at net.minecraft.class_1132.method_3748(class_1132.java:96)
	at net.minecraft.server.MinecraftServer.handler$chl000$modifiedRunLoop(MinecraftServer.java:8390)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:676)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:831)

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Linux (amd64) version 5.15.2-arch1-1
	Java Version: 16.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 990222584 bytes (944 MiB) / 2004877312 bytes (1912 MiB) up to 17179869184 bytes (16384 MiB)
	CPUs: 16
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 13
	Microarchitecture: Coffee Lake
	Frequency (GHz): 3.60
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: GA102 [GeForce RTX 3080]
	Graphics card #0 vendor: NVIDIA Corporation (0x10de)
	Graphics card #0 VRAM (MB): 288.00
	Graphics card #0 deviceId: 0x2206
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 48749.37
	Virtual memory used (MB): 8242.26
	Swap memory total (MB): 32767.00
	Swap memory used (MB): 368.70
	JVM Flags: 2 total; -Xss1M -Xmx16G
	Fabric Mods: 
		accurateblockplacement: Accurate Block Placement 1.0.10
		actuallyunbreaking: Actually Unbreaking 1.17.1-0.4.0
		appliedenergistics2: Applied Energistics 2 9.0.0-beta.1
		architectury: Architectury 2.6.35
		attributefix: Attribute Fix {FABRIC} 1.0.3
		autoconfig1u: Auto Config v1 Updated 3.3.1
		blue_endless_jankson: jankson 1.2.1
		c2me: Concurrent Chunk Management Engine 0.2.0+alpha.5.0
		carpet: Carpet Mod 1.4.51
		cloth-api: Cloth API 2.0.54
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 2.0.54
		cloth-common-events-v1: Cloth Common Events v1 2.0.54
		cloth-config2: Cloth Config v5 5.0.38
		cloth-datagen-api-v1: Cloth Datagen v1 2.0.54
		cloth-scissors-api-v1: Cloth Scissors API v1 2.0.54
		cloth-utils-v1: Cloth Utils v1 2.0.54
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		cullleaves: Cull Leaves 2.3.2
		diggusmaximus: Diggus Maximus 1.5.1-1.17
		dsurround: Â§6Dynamic SurroundingsÂ§r: Â§eFabric Edition 0.0.4
		dynamicfps: Dynamic FPS 2.0.6
		entityculling: EntityCulling-Fabric 1.3.3
		fabric: Fabric API 0.41.0+1.17
		fabric-api-base: Fabric API Base 0.3.0+a02b446313
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.3.0+cbda931818
		fabric-biome-api-v1: Fabric Biome API (v1) 3.2.0+cbda931818
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+a02b446318
		fabric-command-api-v1: Fabric Command API (v1) 1.1.3+5ab9934c88
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afa18
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+cbda931818
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.3.0+cbda931818
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.5+be9da31018
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.11+6cefd57718
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.3.0+57bef5a318
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.10+fc40aa9d18
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afa18
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.7+cbda931818
		fabric-item-api-v1: Fabric Item API (v1) 1.2.4+cbda931818
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.10+b7ab612118
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+cbda931818
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+36b77c3e18
		fabric-language-kotlin: Fabric Language Kotlin 1.6.5+kotlin.1.5.31
		fabric-language-scala: Fabric Language Scala 1.1.0+scala.2.13.6
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.4+a02b44633d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+a02b446318
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afa18
		fabric-models-v0: Fabric Models (v0) 0.3.0+a02b446318
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.13+2e8bd82f18
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.11+a02b446318
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afa18
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.9+cbda931818
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+a02b446318
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+a02b446318
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.11+7931163218
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.4+cbda931818
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.8+cbda931818
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.4+7931163218
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+a02b446313
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.14+4658223018
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.5+7931163218
		fabric-rendering-v1: Fabric Rendering (v1) 1.9.0+7931163218
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.8+a00e834b18
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.4+198a96213d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+cbda931818
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.13+5ab9934c18
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.2+8f2c3e0488
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+a02b446318
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.12+b7ab612118
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.4.0+7931163218
		fabricloader: Fabric Loader 0.11.7
		fake-player-api: Fake Player API 0.2.0
		fallingtree: FallingTree 2.14.2
		ferritecore: FerriteCore 3.0.3
		fiber: fiber 0.23.0-2
		firstperson: FirstpersonModel 2.1.0
		flytre-lib-base: Flytre Lib - Base Module 1.2.0
		flytre-lib-compat: Flytre Lib - Compat Module 1.0.0
		flytre-lib-config: Flytre Lib - Config Module 1.1.0
		flytre-lib-event: Flytre Lib - Event Module 1.0.1
		flytre-lib-gui: Flytre Lib - GUI Module 1.0.0
		flytre-lib-storage: Flytre Lib - Storage Module 2.3.1
		flytre_lib: Flytre Lib 1.3.9
		geckolib3: Geckolib 3.0.19
		hlandbukkit_c2me-fabric_ver_1_17_libs_: libs 0.2.0+alpha.5.0
		hookshot: Hookshot 22.0
		huntingham-hills: Huntingham Hills 1.2.8
		hwg: Happiness is a Warm Gun 1.0.22
		hydrogen: Hydrogen 0.3
		imm_ptl_core: Immersive Portals Core 0.29
		immersive_portals: Immersive Portals 0.29
		indium: Indium 1.0.0+mc1.17.1
		indrev: Industrial Revolution 1.12.0-BETA
		inventoryhud: Inventory HUD + 3.4.1
		iris: Iris 1.1.2+build.9
		ironfurnaces: Iron Furnaces 1.17.1-2.6.1-fabric
		jankson: Jankson 3.0.1+j1.2.0
		java: OpenJDK 64-Bit Server VM 16
		kbootstrap: kbootstrap 0.1.5
		kirin: Kirin UI 1.9.1
		kyrptconfig: Kytpt Config 1.1.10-1.17
		lazydfu: LazyDFU 0.1.2
		libblockattributes: LibBlockAttributes 0.9.0
		libblockattributes_core: LibBlockAttributes (Core) 0.9.0
		libblockattributes_fluids: LibBlockAttributes (Fluids) 0.9.0
		libblockattributes_items: LibBlockAttributes (Items) 0.9.0
		libgui: LibGui 4.2.1+1.17.1
		libninepatch: LibNinePatch 1.1.0
		lightoverlay: Light Overlay 6.0.1
		limitless: limitless 1.5.13
		magna: Magna 0.4.0-1.17.1
		midnightlib: MidnightLib 0.2.9
		minecraft: Minecraft 1.17.1
		mm: Manningham Mills 2.3
		modmenu: Mod Menu 2.0.14
		nbtcrafting: NBT Crafting 2.1.0+mc1.17.1
		net_auoeke_extensions_asm-tree: asm-tree 0.24.0
		net_auoeke_extensions_extensions: extensions 0.24.0
		net_auoeke_reflect: reflect 3.2.0
		net_bytebuddy_byte-buddy-agent: byte-buddy-agent 1.11.21
		net_gudenau_lib_unsafe: unsafe 1.4.3
		notenoughanimations: NotEnoughAnimations 1.4.0
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.5.31
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.5.31
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.5.31
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.5.31
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.2
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.0
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.0
		org_openjdk_nashorn_nashorn-core: nashorn-core 15.3
		patchouli: Patchouli 1.17.1-56-FABRIC-SNAPSHOT
		pipe: Pipe 1.5.0
		presencefootsteps: Presence Footsteps r32-1.17-rc1
		q_misc_util: A Miscellaneous Utility Library from qouteall 0.29
		quarryplus: QuarryPlus 17.0.390
		recipecache: recipecache 0.2.1-1.17.1
		ring_of_attraction: Ring Of Attraction 1.1.14
		roughlyenoughitems: Roughly Enough Items 6.0.307-alpha
		roughlyenoughresources: Roughly Enough Resources 2.2.0
		shulkerboxtooltip: Shulker Box Tooltip 3.0.3+1.17.1
		sodium: Sodium 0.3.2+IRIS2-build.9
		starlight: Starlight 1.0.0+fabric.73f6d37
		step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		stockpile: Stockpile 1.1.5+1.17.1
		team_reborn_energy: Energy 2.0.0-beta1
		transliterationlib: TRansliterationLib 1.2.2
		wands: Building Wands 2.2.8_mc1.17.1
		xaerominimap: Xaero's Minimap 21.21.0
		xaeroworldmap: Xaero's World Map 1.18.1
	Player Count: 1 / 8; [class_3222['FunnyPigRun'/153, l='ServerWorld minecraft:overworld FPR3', x=-8211.94, y=-63.00, z=-37900.96]]
	Data Packs: vanilla, Fabric Mods, file/terralith-v1-6-4.zip, file/FPR, file/EXP_MULT (incompatible)
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'
</details>

**Comment by branchpanic** [comment]
Sorry for the inconvenience. Seems like this will be fixed by #108 whenever I can get around to it
